/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Access-Tokens-Jwt.Login */
        post: operations["auth_access_tokens_jwt_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Access-Tokens-Jwt.Logout */
        post: operations["auth_access_tokens_jwt_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_api_v1_auth__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_api_v1_auth__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_api_v1_auth__id__patch"];
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Request-Token */
        post: operations["verify_request_token_api_v1_auth_request_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Verify */
        post: operations["verify_verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Forgot Password */
        post: operations["reset_forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Reset Password */
        post: operations["reset_reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Users:Get All Users
         * @description <h1>Get a list of all users</h1>
         */
        get: operations["users_get_all_users_api_v1_users__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Categories:Get All Categories
         * @description <h1>Get all categories</h1>
         */
        get: operations["categories_get_all_categories_api_v1_categories__get"];
        put?: never;
        /**
         * Categories:Create A New Category
         * @description <h1>Create a new category</h1>
         */
        post: operations["categories_create_a_new_category_api_v1_categories__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories:Get All Categories With Products */
        get: operations["categories_get_all_categories_with_products_api_v1_categories_all__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Categories:Get Category By Id
         * @description <h1>Get category by ID</h1>
         */
        get: operations["categories_get_category_by_id_api_v1_categories__category_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/sub/{category_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories:Get Category With Subcategories */
        get: operations["categories_get_category_with_subcategories_api_v1_categories_sub__category_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products:Get All Products */
        get: operations["products_get_all_products_api_v1_products__get"];
        put?: never;
        /** Products:Create A New Product */
        post: operations["products_create_a_new_product_api_v1_products__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product By Id */
        get: operations["get_product_by_id_api_v1_products__product_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Product */
        put: operations["update_product_api_v1_products__product_id__put"];
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_v1_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product Partial */
        patch: operations["update_product_partial_api_v1_products__product_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BearerResponse */
        BearerResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** Body_auth_access_tokens_jwt_login_api_v1_auth_login_post */
        Body_auth_access_tokens_jwt_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** Body_reset_forgot_password_api_v1_auth_forgot_password_post */
        Body_reset_forgot_password_api_v1_auth_forgot_password_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_reset_reset_password_api_v1_auth_reset_password_post */
        Body_reset_reset_password_api_v1_auth_reset_password_post: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** Body_verify_request_token_api_v1_auth_request_verify_token_post */
        Body_verify_request_token_api_v1_auth_request_verify_token_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_verify_verify_api_v1_auth_verify_post */
        Body_verify_verify_api_v1_auth_verify_post: {
            /** Token */
            token: string;
        };
        /**
         * CategoryCreate
         * @description Schema for creating a category
         */
        CategoryCreate: {
            /**
             * Category Name
             * @description Unique category name, between 3 and 32 characters.
             */
            name: string;
            /**
             * Category Description
             * @description A short description of the category (optional), between 3 and 128 characters.
             */
            description?: string | null;
            /**
             * Parent Category ID
             * @description ID of the parent category, if this is a subcategory.
             */
            parent_id?: number | null;
        };
        /**
         * CategoryRead
         * @description Schema for reading a category
         */
        CategoryRead: {
            /**
             * Category Name
             * @description Unique category name, between 3 and 32 characters.
             */
            name: string;
            /**
             * Category Description
             * @description A short description of the category (optional), between 3 and 128 characters.
             */
            description?: string | null;
            /**
             * Parent Category ID
             * @description ID of the parent category, if this is a subcategory.
             */
            parent_id?: number | null;
            /**
             * Category ID
             * @description Unique identifier of the category.
             */
            id: number;
        };
        /**
         * CategoryReadList
         * @description Schema for reading a list of categories
         */
        CategoryReadList: components["schemas"]["CategoryRead"][];
        /**
         * CategoryReadListWithProducts
         * @description Schema for reading a list of categories with products
         */
        CategoryReadListWithProducts: components["schemas"]["CategoryReadWithProduct"][];
        /**
         * CategoryReadWithProduct
         * @description Schema for reading a category with a list of products
         */
        CategoryReadWithProduct: {
            /**
             * Category Name
             * @description Unique category name, between 3 and 32 characters.
             */
            name: string;
            /**
             * Category Description
             * @description A short description of the category (optional), between 3 and 128 characters.
             */
            description?: string | null;
            /**
             * Parent Category ID
             * @description ID of the parent category, if this is a subcategory.
             */
            parent_id?: number | null;
            /**
             * Category ID
             * @description Unique identifier of the category.
             */
            id: number;
            /**
             * Category Products
             * @description List of products associated with this category.
             */
            products?: components["schemas"]["ProductRead"][] | null;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProductCreate
         * @description Schema for creating a product
         */
        ProductCreate: {
            /**
             * Product Name
             * @description Full name of the product
             */
            name: string;
            /**
             * Description
             * @description Short description of the product
             */
            description: string;
            /**
             * Price
             * @description Product price
             */
            price: number;
            /**
             * Category ID
             * @description ID of the category the product belongs to
             */
            category_id: number;
        };
        /**
         * ProductRead
         * @description Schema for reading a product
         */
        ProductRead: {
            /**
             * Product Name
             * @description Full name of the product
             */
            name: string;
            /**
             * Description
             * @description Short description of the product
             */
            description: string;
            /**
             * Price
             * @description Product price
             */
            price: number;
            /**
             * Category ID
             * @description ID of the category the product belongs to
             */
            category_id: number;
            /**
             * Product ID
             * @description Unique identifier of the product
             */
            id: number;
        };
        /**
         * ProductReadList
         * @description Schema for reading a list of products
         */
        ProductReadList: components["schemas"]["ProductRead"][];
        /**
         * ProductUpdate
         * @description Schema for updating a product
         */
        ProductUpdate: {
            /**
             * Product Name
             * @description Full name of the product
             */
            name: string;
            /**
             * Description
             * @description Short description of the product
             */
            description: string;
            /**
             * Price
             * @description Product price
             */
            price: number;
            /**
             * Category ID
             * @description ID of the category the product belongs to
             */
            category_id: number;
        };
        /**
         * ProductUpdatePartial
         * @description Schema for partially updating a product
         */
        ProductUpdatePartial: {
            /**
             * Product Name
             * @description Full product name (optional)
             */
            name?: string | null;
            /**
             * Description
             * @description Short product description (optional)
             */
            description?: string | null;
            /**
             * Price
             * @description Product price in rubles (optional)
             */
            price?: number | null;
            /**
             * Category ID
             * @description Category identifier (optional)
             */
            category_id?: number | null;
        };
        /**
         * SubCategoryBase
         * @description Schema for reading subcategories of a selected category
         */
        SubCategoryBase: {
            /**
             * Category Name
             * @description Unique category name, between 3 and 32 characters.
             */
            name: string;
            /**
             * Category Description
             * @description A short description of the category (optional), between 3 and 128 characters.
             */
            description?: string | null;
            /**
             * Parent Category ID
             * @description ID of the parent category, if this is a subcategory.
             */
            parent_id?: number | null;
            /**
             * Category ID
             * @description Unique identifier of the category.
             */
            id: number;
            /**
             * Subcategories
             * @description List of nested subcategories (if any).
             */
            subcategories?: components["schemas"]["CategoryRead"][] | null;
        };
        /**
         * UserCreate
         * @description Schema for creating a new user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email, unique
             * @description User's email (must be unique)
             * @example example@market.io
             */
            email: string;
            /**
             * Password
             * @description User password (minimum 8 characters)
             * @example MyStrongPassword123
             */
            password: string;
            /**
             * Is Active
             * Format: boolean
             * @description Indicates whether the user is active
             * @default true
             * @example true
             */
            readonly is_active: boolean | null;
            /**
             * Is Superuser
             * Format: boolean
             * @description Indicates whether the user is a superuser
             * @default false
             * @example false
             */
            readonly is_superuser: boolean | null;
            /**
             * Is Verified
             * Format: boolean
             * @description Indicates whether the email is verified
             * @default false
             * @example true
             */
            readonly is_verified: boolean | null;
            /**
             * Username
             * Format: string
             * @description Username (up to 32 characters)
             */
            username?: string | null;
            /**
             * First Name
             * Format: string
             * @description First name (up to 32 characters)
             */
            first_name?: string | null;
            /**
             * Last Name
             * Format: string
             * @description Last name (up to 32 characters)
             */
            last_name?: string | null;
            /**
             * Middle Name
             * Format: string
             * @description Middle name (up to 32 characters)
             */
            middle_name?: string | null;
            /**
             * Birth Date
             * Format: date, YYYY-MM-DD
             * @description Birth date (in format 'YYYY-MM-DD')
             * @example 2020-01-20
             */
            birth_date?: string | null;
            /**
             * Password Repeat
             * @description Password confirmation
             * @example MyStrongPassword123
             */
            password_repeat: string;
        };
        /**
         * UserRead
         * @description Schema for reading a user, including base fields from FastAPI Users.
         */
        UserRead: {
            /**
             * Id
             * Format: integer, unique
             * @description Unique user identifier
             */
            readonly id: number;
            /**
             * Email
             * Format: email, unique
             * @description User's email (must be unique)
             * @example example@market.io
             */
            email: string;
            /**
             * Is Active
             * Format: boolean
             * @description Indicates whether the user is active
             * @default true
             * @example true
             */
            readonly is_active: boolean | null;
            /**
             * Is Superuser
             * Format: boolean
             * @description Indicates whether the user is a superuser
             * @default false
             * @example false
             */
            readonly is_superuser: boolean | null;
            /**
             * Is Verified
             * Format: boolean
             * @description Indicates whether the email is verified
             * @default false
             * @example true
             */
            readonly is_verified: boolean | null;
            /**
             * Username
             * Format: string
             * @description Username (up to 32 characters)
             */
            username?: string | null;
            /**
             * First Name
             * Format: string
             * @description First name (up to 32 characters)
             */
            first_name?: string | null;
            /**
             * Last Name
             * Format: string
             * @description Last name (up to 32 characters)
             */
            last_name?: string | null;
            /**
             * Middle Name
             * Format: string
             * @description Middle name (up to 32 characters)
             */
            middle_name?: string | null;
            /**
             * Birth Date
             * Format: date, YYYY-MM-DD
             * @description Birth date (in format 'YYYY-MM-DD')
             * @example 2020-01-20
             */
            birth_date?: string | null;
            /**
             * Registered On
             * Format: datetime
             * @description User registration date and time
             * @example 22/11/2001, 19:14:01
             */
            readonly registered_on: string;
        };
        /**
         * UserReadList
         * @description Schema for reading a list of users.
         */
        UserReadList: components["schemas"]["UserRead"][];
        /**
         * UserUpdate
         * @description Schema for updating user data.
         */
        UserUpdate: {
            /**
             * Password
             * @description New user password
             * @example MyStrongPassword123
             */
            password?: string | null;
            /**
             * Email
             * Format: email, unique
             * @description Updated user email
             * @example example@market.io
             */
            email?: string | null;
            /**
             * Is Active
             * Format: boolean
             * @description Change user active status
             * @example false
             */
            is_active?: boolean | null;
            /**
             * Is Superuser
             * Format: boolean
             * @description Change user superuser status
             * @example true
             */
            is_superuser?: boolean | null;
            /**
             * Is Verified
             * Format: boolean
             * @description Indicates if the user's email is verified
             * @example true
             */
            is_verified?: boolean | null;
            /**
             * Username
             * Format: string
             * @description Updated username
             */
            username?: string | null;
            /**
             * First Name
             * Format: string
             * @description Updated first name
             */
            first_name?: string | null;
            /**
             * Last Name
             * Format: string
             * @description Updated last name
             */
            last_name?: string | null;
            /**
             * Middle Name
             * Format: string
             * @description Updated middle name
             */
            middle_name?: string | null;
            /**
             * Birth Date
             * Format: date, YYYY-MM-DD
             * @description Updated birth date
             * @example 2020-01-20
             */
            birth_date?: string | null;
            /**
             * Password Repeat
             * @description Password confirmation
             * @example MyStrongPassword123
             */
            password_repeat?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_access_tokens_jwt_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_access_tokens_jwt_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTIyMWZmYzktNjQwZi00MzcyLTg2ZDMtY2U2NDJjYmE1NjAzIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTcxNTA0MTkzfQ.M10bjOe45I5Ncu_uXvOmVV8QxnL-nZfcH96U90JaocI",
                     *       "token_type": "bearer"
                     *     } */
                    "application/json": components["schemas"]["BearerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_access_tokens_jwt_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_api_v1_auth__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_api_v1_auth__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_api_v1_auth__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_request_token_api_v1_auth_request_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_request_token_api_v1_auth_request_verify_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_verify_api_v1_auth_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_forgot_password_api_v1_auth_forgot_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_reset_password_api_v1_auth_reset_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_get_all_users_api_v1_users__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReadList"];
                };
            };
            /** @description Missing token or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_get_all_categories_api_v1_categories__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryReadList"];
                };
            };
            /** @description There are no categories */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_create_a_new_category_api_v1_categories__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_get_all_categories_with_products_api_v1_categories_all__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryReadListWithProducts"];
                };
            };
            /** @description There are no categories */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_get_category_by_id_api_v1_categories__category_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description The category does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_get_category_with_subcategories_api_v1_categories_sub__category_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubCategoryBase"];
                };
            };
            /** @description The category does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    products_get_all_products_api_v1_products__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductReadList"];
                };
            };
        };
    };
    products_create_a_new_product_api_v1_products__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_by_id_api_v1_products__product_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_partial_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdatePartial"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
