/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Access-Tokens-Jwt.Login */
        post: operations["auth_access_tokens_jwt_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Access-Tokens-Jwt.Logout */
        post: operations["auth_access_tokens_jwt_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_api_v1_auth__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_api_v1_auth__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_api_v1_auth__id__patch"];
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Request-Token */
        post: operations["verify_request_token_api_v1_auth_request_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify:Verify */
        post: operations["verify_verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Forgot Password */
        post: operations["reset_forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset:Reset Password */
        post: operations["reset_reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/all_users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Get All Users */
        get: operations["users_get_all_users_api_v1_users_all_users__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories:Get All Categories */
        get: operations["categories_get_all_categories_api_v1_categories__get"];
        put?: never;
        /** Categories:Create A New Category */
        post: operations["categories_create_a_new_category_api_v1_categories__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories:Get All Categories With Products */
        get: operations["categories_get_all_categories_with_products_api_v1_categories_all__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories:Get Category By Id */
        get: operations["categories_get_category_by_id_api_v1_categories__category_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/sub/{category_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories:Get Category With Subcategories */
        get: operations["categories_get_category_with_subcategories_api_v1_categories_sub__category_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products:Get All Products */
        get: operations["products_get_all_products_api_v1_products__get"];
        put?: never;
        /** Products:Create A New Product */
        post: operations["products_create_a_new_product_api_v1_products__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product By Id */
        get: operations["get_product_by_id_api_v1_products__product_id___get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Product */
        put: operations["update_product_api_v1_products__product_id__put"];
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_v1_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product Partial */
        patch: operations["update_product_partial_api_v1_products__product_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BearerResponse */
        BearerResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** Body_auth_access_tokens_jwt_login_api_v1_auth_login_post */
        Body_auth_access_tokens_jwt_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** Body_reset_forgot_password_api_v1_auth_forgot_password_post */
        Body_reset_forgot_password_api_v1_auth_forgot_password_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_reset_reset_password_api_v1_auth_reset_password_post */
        Body_reset_reset_password_api_v1_auth_reset_password_post: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** Body_verify_request_token_api_v1_auth_request_verify_token_post */
        Body_verify_request_token_api_v1_auth_request_verify_token_post: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Body_verify_verify_api_v1_auth_verify_post */
        Body_verify_verify_api_v1_auth_verify_post: {
            /** Token */
            token: string;
        };
        /**
         * CategoryCreate
         * @description Схема для создания категории
         */
        CategoryCreate: {
            /**
             * Название категории
             * @description Уникальное название категории, от 3 до 32 символов.
             */
            name: string;
            /**
             * Описание категории
             * @description Краткое описание категории (необязательно), от 3 до 128 символов.
             */
            description?: string | null;
            /**
             * ID родительской категории
             * @description ID родительской категории, если эта категория является подкатегорией.
             */
            parent_id?: number | null;
        };
        /**
         * CategoryRead
         * @description Схема для чтения категории
         */
        CategoryRead: {
            /**
             * Название категории
             * @description Уникальное название категории, от 3 до 32 символов.
             */
            name: string;
            /**
             * Описание категории
             * @description Краткое описание категории (необязательно), от 3 до 128 символов.
             */
            description?: string | null;
            /**
             * ID родительской категории
             * @description ID родительской категории, если эта категория является подкатегорией.
             */
            parent_id?: number | null;
            /**
             * ID категории
             * @description Уникальный идентификатор категории.
             */
            id: number;
        };
        /**
         * CategoryReadList
         * @description Схема для чтения списка категорий
         */
        CategoryReadList: components["schemas"]["CategoryRead"][];
        /**
         * CategoryReadListWithProducts
         * @description Схема для чтения списка категорий с продуктами
         */
        CategoryReadListWithProducts: components["schemas"]["CategoryReadWithProduct"][];
        /**
         * CategoryReadWithProduct
         * @description Схема для чтения категории со списком продуктов
         */
        CategoryReadWithProduct: {
            /**
             * Название категории
             * @description Уникальное название категории, от 3 до 32 символов.
             */
            name: string;
            /**
             * Описание категории
             * @description Краткое описание категории (необязательно), от 3 до 128 символов.
             */
            description?: string | null;
            /**
             * ID родительской категории
             * @description ID родительской категории, если эта категория является подкатегорией.
             */
            parent_id?: number | null;
            /**
             * ID категории
             * @description Уникальный идентификатор категории.
             */
            id: number;
            /**
             * Продукты категории
             * @description Список продуктов, связанных с этой категорией.
             */
            products?: components["schemas"]["ProductRead"][] | null;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProductCreate
         * @description Схема для создания продукта
         */
        ProductCreate: {
            /**
             * Название товара
             * @description Полное название товара
             */
            name: string;
            /**
             * Описание
             * @description Краткое описание товара
             */
            description: string;
            /**
             * Цена
             * @description Цена товара
             */
            price: number;
            /**
             * ID категории
             * @description Идентификатор категории, к которой относится товар
             */
            category_id: number;
        };
        /**
         * ProductRead
         * @description Схема для чтения продукта
         */
        ProductRead: {
            /**
             * Название товара
             * @description Полное название товара
             */
            name: string;
            /**
             * Описание
             * @description Краткое описание товара
             */
            description: string;
            /**
             * Цена
             * @description Цена товара
             */
            price: number;
            /**
             * ID категории
             * @description Идентификатор категории, к которой относится товар
             */
            category_id: number;
            /**
             * ID товара
             * @description Уникальный идентификатор товара
             */
            id: number;
        };
        /**
         * ProductReadList
         * @description Схема для чтения списка продуктов
         */
        ProductReadList: components["schemas"]["ProductRead"][];
        /**
         * ProductUpdate
         * @description Схема для обновления продукта
         */
        ProductUpdate: {
            /**
             * Название товара
             * @description Полное название товара
             */
            name: string;
            /**
             * Описание
             * @description Краткое описание товара
             */
            description: string;
            /**
             * Цена
             * @description Цена товара
             */
            price: number;
            /**
             * ID категории
             * @description Идентификатор категории, к которой относится товар
             */
            category_id: number;
        };
        /**
         * ProductUpdatePartial
         * @description Схема для частичного обновления продукта
         */
        ProductUpdatePartial: {
            /**
             * Название товара
             * @description Полное название товара (опционально)
             */
            name?: string | null;
            /**
             * Описание
             * @description Краткое описание товара (опционально)
             */
            description?: string | null;
            /**
             * Цена
             * @description Цена товара в рублях (опционально)
             */
            price?: number | null;
            /**
             * ID категории
             * @description Идентификатор категории (опционально)
             */
            category_id?: number | null;
        };
        /**
         * SubCategoryBase
         * @description Схема для чтения подкатегорий выбраной категории
         */
        SubCategoryBase: {
            /**
             * Название категории
             * @description Уникальное название категории, от 3 до 32 символов.
             */
            name: string;
            /**
             * Описание категории
             * @description Краткое описание категории (необязательно), от 3 до 128 символов.
             */
            description?: string | null;
            /**
             * ID родительской категории
             * @description ID родительской категории, если эта категория является подкатегорией.
             */
            parent_id?: number | null;
            /**
             * ID категории
             * @description Уникальный идентификатор категории.
             */
            id: number;
            /**
             * Подкатегории
             * @description Список вложенных подкатегорий (если есть).
             */
            subcategories?: components["schemas"]["CategoryRead"][] | null;
        };
        /**
         * Профиль пользователя
         * @description Схема для создания нового пользователя.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             * @description Электронная почта пользователя (уникальная)
             */
            email: string;
            /**
             * Password
             * @description Пароль пользователя (не менее 8 символов)
             */
            password: string;
            /**
             * Is Active
             * @description Признак того, что пользователь активен
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @description Признак того, что пользователь является суперпользователем
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @description Признак того, что электронная почта подтверждена
             * @default false
             */
            is_verified: boolean | null;
            /**
             * Username
             * @description Имя пользователя (никнейм)
             */
            username?: string | null;
            /**
             * First Name
             * @description Имя
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Фамилия
             */
            last_name?: string | null;
            /**
             * Middle Name
             * @description Отчество
             */
            middle_name?: string | null;
            /**
             * Birth Date
             * @description Дата рождения
             */
            birth_date?: string | null;
        };
        /**
         * Профиль пользователя
         * @description Расширенная схема чтения пользователя, включая базовые поля из FastAPI Users.
         */
        UserRead: {
            /**
             * Id
             * @description Уникальный идентификатор пользователя
             */
            id: number;
            /**
             * Email
             * Format: email
             * @description Электронная почта пользователя (уникальная)
             */
            email: string;
            /**
             * Is Active
             * @description Признак того, что пользователь активен
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @description Признак того, что пользователь является суперпользователем
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @description Признак того, что электронная почта подтверждена
             * @default false
             */
            is_verified: boolean | null;
            /**
             * Username
             * @description Имя пользователя (никнейм)
             */
            username?: string | null;
            /**
             * First Name
             * @description Имя
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Фамилия
             */
            last_name?: string | null;
            /**
             * Middle Name
             * @description Отчество
             */
            middle_name?: string | null;
            /**
             * Birth Date
             * @description Дата рождения
             */
            birth_date?: string | null;
            /**
             * Registered On
             * Format: date-time
             * @description Дата и время регистрации пользователя
             */
            registered_on: string;
        };
        /**
         * Профиль пользователя
         * @description Схема для обновления данных пользователя.
         */
        UserUpdate: {
            /**
             * Password
             * @description Новый пароль пользователя
             */
            password?: string | null;
            /**
             * Email
             * @description Обновлённая электронная почта пользователя
             */
            email?: string | null;
            /**
             * Is Active
             * @description Изменить статус активности пользователя
             */
            is_active?: boolean | null;
            /**
             * Is Superuser
             * @description Изменить статус суперпользователя
             */
            is_superuser?: boolean | null;
            /**
             * Is Verified
             * @description Подтверждена ли почта пользователя
             */
            is_verified?: boolean | null;
            /**
             * Username
             * @description Обновлённое имя пользователя
             */
            username?: string | null;
            /**
             * First Name
             * @description Обновлённое имя
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Обновлённая фамилия
             */
            last_name?: string | null;
            /**
             * Middle Name
             * @description Обновлённое отчество
             */
            middle_name?: string | null;
            /**
             * Birth Date
             * @description Обновлённая дата рождения
             */
            birth_date?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_access_tokens_jwt_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_access_tokens_jwt_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BearerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_access_tokens_jwt_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_api_v1_auth__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_api_v1_auth__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_api_v1_auth__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_request_token_api_v1_auth_request_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_request_token_api_v1_auth_request_verify_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_verify_verify_api_v1_auth_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_forgot_password_api_v1_auth_forgot_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_reset_reset_password_api_v1_auth_reset_password_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_get_all_users_api_v1_users_all_users__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Unauthorized: Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden: User is not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_get_all_categories_api_v1_categories__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryReadList"];
                };
            };
        };
    };
    categories_create_a_new_category_api_v1_categories__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_get_all_categories_with_products_api_v1_categories_all__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryReadListWithProducts"];
                };
            };
        };
    };
    categories_get_category_by_id_api_v1_categories__category_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_get_category_with_subcategories_api_v1_categories_sub__category_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubCategoryBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    products_get_all_products_api_v1_products__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductReadList"];
                };
            };
        };
    };
    products_create_a_new_product_api_v1_products__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_by_id_api_v1_products__product_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_partial_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdatePartial"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
